# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: ie-bank-frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  FRONTEND_WEBAPP_DEV: betroy-fe-uat

jobs:
  build-uat:
    if: github.event.pull_request.base.ref == 'main' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'   # Ensure Node.js version is consistent

      - name: npm install, build, and test (UAT)
        run: |
          npm install
          npm run build:uat ## This command will build the Vue.js app using .env.uat variables

      - name: Upload artifact for deployment job (UAT)
        uses: actions/upload-artifact@v4
        with:
          name: node-app-uat
          path: dist-uat/

  deploy-uat:
    runs-on: ubuntu-latest
    needs: build-uat
    environment:
      name: 'UAT'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build-uat job
        uses: actions/download-artifact@v4
        with:
          name: node-app-uat

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Web App - UAT'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.FRONTEND_WEBAPP }}
          package: .